#!/usr/bin/env bash

if [ ! -f "$1" ]; then
    echo "Входной файл не найден"
    exit 1
fi

if [ "$1" = "$2" ]; then
    echo "Входной и выходной файлы должны отличаться"
    exit 1
fi

sed $'s/    /\t/g' "$1" > "$2"
